services:
  # ui
  pii-detector-standalone-ui:
    container_name: pii-detector-standalone-ui
    build:
      context: ../
      dockerfile: ./docker/ui.DockerFile
    environment:
      - NODE_ENV=production
      - VITE_PII_DETECTOR_API_ENDPOINT=${VITE_PII_DETECTOR_API_ENDPOINT}
    restart: unless-stopped
    expose:
      - 80
    ports:
      - '3000:80'
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s